pipeline:

  publish:
    image: gradle:5.5.1-jdk8
    secrets: [ drill_username, drill_password ]
    commands:
      - gradle :plugins:drill-coverage-plugin:buildToDistr
      - gradle :drill-admin:jib
          -Djib.to.auth.username=$${DRILL_USERNAME}
          -Djib.to.auth.password=$${DRILL_PASSWORD}
          -Djib.to.tags=coverage-latest
          -Djib.extraDirectories.paths=$${PWD}/distr
    when:
      branch:
        - feature/EPMDJ-398-drone
