pipeline:

  build:
    image: gradle:5.5.1-jdk8
    environment:
      KONAN_DATA_DIR: /home/gradle/.gradle/konan
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    commands:
      - gradle build check

  publish:
    image: gradle:5.5.1-jdk8
    secrets: [ drill_username, drill_password, bintray_user, bintray_api]
    commands:
      - gradle :drill-admin:downloadPlugins
      - gradle :drill-admin:jib
          -Djib.to.auth.username=$${DRILL_USERNAME}
          -Djib.to.auth.password=$${DRILL_PASSWORD}
          -Djib.to.tags=coverage-latest
          -Djib.extraDirectories.paths=$${PWD}/distr,$${PWD}/drill-admin/ssl
      - gradle :drill-admin:publishAdminPublicationToMavenRepository
        -PbintrayUser=$${BINTRAY_USER}
        -PbintrayApiKey=$${BINTRAY_API}
    when:
      branch:
        - develop
      event:
        exclude:
          - pull_request
