kind: pipeline
name: admin

steps:
  - name: build-and-publish
    image: gradle:5.4.1-jdk8
    secrets: [ drill_username, drill_password, docker_username ]
    environment:
      XX_USERNAME:
        from secret: drill_username
      KONAN_DATA_DIR: /home/gradle/.gradle/konan
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    commands:
      - env
      - echo $DRILL_USERNAME
      - echo $KONAN_DATA_DIR
      - echo $DOCKER_USERNAME
    when:
      branch:
        - feature/EPMDJ-398-drone-io