kind: pipeline
name: agent

steps:
  - name: build
    image: gradle:5.4.1-jdk8
    environment:
      KONAN_DATA_DIR: /home/gradle/.gradle/konan
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    commands:
      - gradle :drill-agent:build
  - name: check
    image: gradle:5.4.1-jdk8
    environment:
      KONAN_DATA_DIR: /home/gradle/.gradle/konan
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    commands:
      - gradle :drill-agent:check
---
kind: pipeline
name: admin

steps:
  - name: build
    image: gradle:5.4.1-jdk8
    commands:
      - gradle :drill-admin:build
  - name: check
    image: gradle:5.4.1-jdk8
    environment:
      KONAN_DATA_DIR: /home/gradle/.gradle/konan
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    commands:
      - gradle :drill-admin:check
