version: '3'

services:
  # requires mongodb container named "drillmongodb" with network "drill4j-dev-network"
  drill-admin:
    build:
      context: ..
      dockerfile: drill-admin/Dockerfile
    ports:
      - 8090:8090
      - 5006:5006
    networks:
      - drill4j-dev-network
    environment:
      - isDocker=true
      - DRILL_HOME=/drill
    restart: always

  postgresdb:
    image:
      postgres:11.3
    restart:
      always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=drill_base


networks:
  drill4j-dev-network:
    external:
      name: drill4j-dev-network
