version: '3'
services:
  fullbuild:
    image: 'igorkuzminykh/drill-platform:2.0'
    volumes:
      - '../:/app'
    command: >
      bash -c "./gradlew build
      && ./gradlew buildAgent
      && ./gradlew buildCoveragePluginDev"
  drillmongodb:
    image: 'mongo'
    restart: always
    ports:
      - 27017:27017
    networks:
      - drill4j-dev-network
  drill-agent:
    image: 'igorkuzminykh/drill-platform:2.0'
    volumes:
      - '../:/app'
    command: ./gradlew runAgent --project-cache-dir .gradle_agent
    restart: always
    networks:
      - drill4j-dev-network
  drill-admin:
    depends_on:
      - drill-agent
    image: 'igorkuzminykh/drill-platform:2.0'
    volumes:
      - '../:/app'
    command: ./gradlew runDrillAdmin --project-cache-dir .gradle_admin
    ports:
      - 8090:8090
    networks:
      - drill4j-dev-network
    environment:
      - isDocker=true
    restart: always

networks:
  drill4j-dev-network:
    external:
      name: drill4j-dev-network