package com.epam.drill.common

val firstName = arrayOf(
    "Crystal",
    "Demure",
    "Dissembling",
    "Gorgeous",
    "Hilarious",
    "Sonorous",
    "Sophisticated",
    "Twinkling",
    "Wonderful",
    "Astonishing",
    "Delightful",
    "Lovely",
    "Fancy",
    "Shiny",
    "Apple",
    "Nectarine",
    "Avocado",
    "Orange",
    "Apricot",
    "Pear",
    "Banana",
    "Papaya",
    "Pineapple",
    "Peach",
    "Grapefruit",
    "Plum",
    "Grapes",
    "Persimmon",
    "Kiwi",
    "Pomegranate",
    "Lime",
    "Lemon",
    "Quince",
    "Mango",
    "Tangerine",
    "Melon"
)

val lastName = arrayOf(
    "Drill",
    "Delicacy",
    "Destiny",
    "Eloquence",
    "Eternity",
    "Felicity",
    "Infinity",
    "Insouciance",
    "Languor",
    "Lassitude",
    "Nemesis",
    "Oblivion",
    "Passion",
    "Serendipity",
    "Solitude",
    "Blossom",
    "Bumblebee",
    "Butterfly",
    "Cynosure",
    "Galaxy",
    "Incandescence",
    "Lullaby",
    "Sunshine",
    "Sweetheart",
    "Syzygy",
    "Elision"
)

fun generatePonyName() = "${firstName[(0 until firstName.size).random()]} ${lastName[(0 until lastName.size).random()]}"